/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package IHM;

import beans.ReleveMeteo;
import com.jtattoo.plaf.JTattooUtilities;
import com.toedter.calendar.JCalendar;
import com.toedter.calendar.JDayChooser;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import controller.Controller;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.UIManager;
import manager.manager;
        

/**
 *
 * @author mabrchaouen
 */
public class Smarti extends javax.swing.JFrame {

    private static final long serialVersionUID = 1L;
   // public JPanel panel;

    /**
     *
     */
    public static String nom;

    /**
     *
     */
    public static String anne;

    /**
     *
     */
    public static String m,

    /**
     *
     */
    j;

    /**
     *
     */
    public static String an2;

    /**
     *
     */
    public static String m2,

    /**
     *
     */
    j2;

    /**
     *
     */
    public static String comp;
    
    /**
     * Creates new form Smarti
     */
    public Smarti() {
        initComponents();
        jour.setEditable(false);
        mois.setEditable(true);
        annee.setEditable(false);
        jour2.setEditable(true);
        moi2.setEditable(true);
        annee2.setEditable(true);
        afficherdonn.setEnabled(false);
       
        graphMois.setEnabled(false);
        grapheAnnee.setEnabled(false);
        btnload.setEnabled(false);
      
        
        
        
        
        
        }
   
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jColorChooser1 = new javax.swing.JColorChooser();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        buttonGroup6 = new javax.swing.ButtonGroup();
        buttonGroup7 = new javax.swing.ButtonGroup();
        buttonGroup8 = new javax.swing.ButtonGroup();
        buttonGroup9 = new javax.swing.ButtonGroup();
        buttonGroup10 = new javax.swing.ButtonGroup();
        buttonGroup11 = new javax.swing.ButtonGroup();
        mois2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jourcal = new com.toedter.calendar.JDayChooser();
        lbstation = new javax.swing.JLabel();
        combo = new javax.swing.JComboBox<>();
        moiscal = new com.toedter.calendar.JMonthChooser();
        anneecal = new com.toedter.calendar.JYearChooser();
        lbmois = new javax.swing.JLabel();
        mois = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jour = new javax.swing.JTextField();
        lblannee = new javax.swing.JLabel();
        annee = new javax.swing.JTextField();
        btnconf = new javax.swing.JButton();
        btnload = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        listemoyenne = new javax.swing.JList<>();
        afficherdonn = new javax.swing.JButton();
        graphMois = new javax.swing.JButton();
        grapheAnnee = new javax.swing.JButton();
        btnaff = new javax.swing.JButton();
        btnst = new javax.swing.JButton();
        btnxt = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        ecarttypeT = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        ecarttypeN = new javax.swing.JTextField();
        ecarttypeH = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jourcal2 = new com.toedter.calendar.JDayChooser();
        moiscal2 = new com.toedter.calendar.JMonthChooser();
        anneecal2 = new com.toedter.calendar.JYearChooser();
        jLabel4 = new javax.swing.JLabel();
        moi2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jour2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        annee2 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        listcomp = new javax.swing.JList<>();
        btnconf2 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        listcompmoisannee = new javax.swing.JList<>();
        jButton2 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        ecarttemp1 = new javax.swing.JTextField();
        ecarttemp2 = new javax.swing.JTextField();
        nebultemp1 = new javax.swing.JTextField();
        nebultemp2 = new javax.swing.JTextField();
        humidtemp1 = new javax.swing.JTextField();
        humidtemp2 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("                                                                                  SMARTCLIMATE");

        lbstation.setText("Station");

        combo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ABBEVILLE", "LILLE-LESQUIN", "PTEDELAHAGUE", "CAEN-CARPIQUET", "ROUEN-BOOS", "REIMS-PRUNAY", "BREST-GUIPAVAS", "PLOUMANAC'H", "RENNES-STJACQUES", "ALENCON", "ORLY", "TROYES-BARBEREY" }));
        combo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboActionPerformed(evt);
            }
        });

        lbmois.setText("Mois");

        mois.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moisActionPerformed(evt);
            }
        });

        jLabel2.setText("Jour");

        jour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jourActionPerformed(evt);
            }
        });

        lblannee.setText("Année");

        btnconf.setText("confirmer");
        btnconf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnconfActionPerformed(evt);
            }
        });

        btnload.setText("Charger");
        btnload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnloadActionPerformed(evt);
            }
        });

        jLabel8.setText("Moyenne :");

        listemoyenne.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Mois", "Jour", "Jour Detaillé", "Mois Detaillé", "Année Detaillée" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(listemoyenne);

        afficherdonn.setText("Afficher");
        afficherdonn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                afficherdonnActionPerformed(evt);
            }
        });

        graphMois.setText("Courbe Mois");
        graphMois.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                graphMoisActionPerformed(evt);
            }
        });

        grapheAnnee.setText("Courbe Année");
        grapheAnnee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                grapheAnneeActionPerformed(evt);
            }
        });

        btnaff.setText("AFFICHER");
        btnaff.setEnabled(false);
        btnaff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaffActionPerformed(evt);
            }
        });

        btnst.setText("STATIONS");
        btnst.setEnabled(false);
        btnst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnstActionPerformed(evt);
            }
        });

        btnxt.setText("QUITTER");
        btnxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnxtActionPerformed(evt);
            }
        });

        jLabel6.setText("Courbe :");

        jLabel10.setText("Ecart-Type :");

        ecarttypeT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ecarttypeTActionPerformed(evt);
            }
        });

        jLabel11.setText("Temperature:");

        jLabel12.setText("Nebulisoté :");

        jLabel13.setText("Humidité :  ");

        ecarttypeN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ecarttypeNActionPerformed(evt);
            }
        });

        ecarttypeH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ecarttypeHActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(68, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lbstation)
                                .addGap(29, 29, 29)
                                .addComponent(combo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jourcal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(moiscal, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(anneecal, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(49, 49, 49))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lbmois, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(mois, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jour, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(btnconf, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(lblannee)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(annee, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(btnload, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(52, 52, 52)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(51, 51, 51)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel6)
                                    .addComponent(grapheAnnee, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(graphMois, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(43, 43, 43)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel13))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(ecarttypeT, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
                                    .addComponent(ecarttypeN)
                                    .addComponent(ecarttypeH))
                                .addGap(22, 22, 22))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(afficherdonn, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnaff, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnst, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(240, 240, 240)
                        .addComponent(btnxt, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(88, 88, 88))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lbstation)
                                    .addComponent(combo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(moiscal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(anneecal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblannee)
                                    .addComponent(annee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(mois, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbmois))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2))
                                .addGap(28, 28, 28)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(afficherdonn, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(btnconf, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnload, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jourcal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jLabel6)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(graphMois)
                                    .addComponent(jLabel11)
                                    .addComponent(ecarttypeT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(grapheAnnee)
                                        .addComponent(ecarttypeN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel12))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel13)
                                    .addComponent(ecarttypeH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnxt)
                    .addComponent(btnst, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnaff, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36))
        );

        jTabbedPane1.addTab("Données", jPanel1);

        jLabel4.setText("Mois");

        jLabel3.setText("Jour");

        jLabel5.setText("Année");

        listcomp.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Temperature", "Humidité", "Nébulosité" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(listcomp);

        btnconf2.setText("Confirmer");
        btnconf2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnconf2ActionPerformed(evt);
            }
        });

        jLabel7.setText("Choix :");

        jLabel9.setText("Par mois ou année ?");

        listcompmoisannee.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Jour", "Mois", "Année" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(listcompmoisannee);

        jButton2.setText("comparer");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel14.setText("Ecart-Type :");

        jLabel15.setText("Date 1 :");

        jLabel16.setText("Date 2 :");

        ecarttemp1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ecarttemp1ActionPerformed(evt);
            }
        });

        humidtemp1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                humidtemp1ActionPerformed(evt);
            }
        });

        jLabel17.setText("Temperature :");

        jLabel18.setText("Nebulosité :");

        jLabel19.setText("Humidité :");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jourcal2, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(moiscal2, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(moi2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(annee2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(anneecal2, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jour2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnconf2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2))
                        .addGap(41, 41, 41)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17)
                            .addComponent(jLabel18)
                            .addComponent(jLabel19)))
                    .addComponent(jLabel9))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(nebultemp1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ecarttemp1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(humidtemp1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(ecarttemp2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nebultemp2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(humidtemp2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel16)))))
                .addContainerGap(117, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(moiscal2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(moi2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jour2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(jLabel16))
                        .addGap(8, 8, 8)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ecarttemp1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17)
                            .addComponent(ecarttemp2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(nebultemp1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nebultemp2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(humidtemp1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel19)
                            .addComponent(humidtemp2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(anneecal2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel7)
                                .addComponent(jLabel9)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel5)
                                .addComponent(annee2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(47, 47, 47)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton2)
                            .addComponent(btnconf2)))
                    .addComponent(jourcal2, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(64, 104, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Comparaison", jPanel2);

        javax.swing.GroupLayout mois2Layout = new javax.swing.GroupLayout(mois2);
        mois2.setLayout(mois2Layout);
        mois2Layout.setHorizontalGroup(
            mois2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mois2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mois2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mois2Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 573, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jTabbedPane1)))
        );
        mois2Layout.setVerticalGroup(
            mois2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mois2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mois2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(mois2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnconf2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnconf2ActionPerformed
        // TODO add your handling code here:
        jour2.setText(""+jourcal2.getDay());
        moi2.setText(""+(moiscal2.getMonth()+1));
        annee2.setText(""+anneecal2.getYear());
    }//GEN-LAST:event_btnconf2ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if(listcompmoisannee.getSelectedValue()=="Mois"){
                if(!(mois.getText().equals(moi2.getText()))){
            JOptionPane.showMessageDialog(null,
                "vous devez comparer 2 mois identiques ","warning"
                ,JOptionPane.WARNING_MESSAGE);
        }

        else{
            comp=listcomp.getSelectedValue();

            ArrayList<ReleveMeteo> x = new ArrayList<>();
            ArrayList<ReleveMeteo> x1 = new ArrayList<>();

            j = jour.getText();
            nom = (String) combo.getSelectedItem();
            anne = annee.getText();
            m = mois.getText();
            if(m.isEmpty()) {m="";}
            else if(Integer.parseInt(m)<10) {m=""+0+m;}

            Controller c = new Controller();
            try {ecarttemp1.setText("");
                nebultemp1.setText("");
                humidtemp1.setText("");

                c.ChargerFichier();
                c.RecupererDonneesFichier();
                c.recupererDonneesTousjours();
                c.caluclecartypeT();
                 
                ecarttemp1.setText(""+c.getecartT());
                nebultemp1.setText(""+c.getecartN());
                humidtemp1.setText(""+c.getecartH());
                //c.affichegraph();
                x=c.getStationRecherchee();

                System.out.println("****************************** hehe  "+c.getStationRecherchee().get(0).getTemperature()) ;
                anne = annee2.getText();
                m = moi2.getText();
                if(m.isEmpty()) m="";
                else   if(Integer.parseInt(m)<10) m=""+0+m;
                j = jour2.getText();
                Controller c1 = new Controller();
                c1.ChargerFichier();
                c1.RecupererDonneesFichier();
                c1.recupererDonneesTousjours();
                c1.caluclecartypeT();
                ecarttemp2.setText("");
                nebultemp2.setText("");
                humidtemp2.setText("");
                ecarttemp2.setText(""+c1.getecartT());
                nebultemp2.setText(""+c1.getecartN());
                humidtemp2.setText(""+c1.getecartH());
                x1=c1.getStationRecherchee();
                System.out.println("****************************** hehe  "+c1.getStationRecherchee().get(0).getTemperature()) ;

                // c1.affichegraph();
                manager manager = new manager();
                manager.comparaisongraph(x,x1,comp);

            } catch (IOException ex) {
                Logger.getLogger(Smarti.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
        }
        else if(listcompmoisannee.getSelectedValue()=="Année"){
          comp=listcomp.getSelectedValue();

        ArrayList<ReleveMeteo> x = new ArrayList<>();
        ArrayList<ReleveMeteo> x1 = new ArrayList<>();

        j = jour.getText();
        nom = (String) combo.getSelectedItem();
        anne = annee.getText();
        m ="";
        if(m.isEmpty()) {m="";}
        else if(Integer.parseInt(m)<10) {m=""+0+m;}

        Controller c = new Controller();
        try { ecarttemp1.setText("");
                nebultemp1.setText("");
                humidtemp1.setText("");
                 ecarttemp2.setText("");
                nebultemp2.setText("");
                humidtemp2.setText("");

            c.ChargerFichier();
            c.RecupererDonneesFichier();
            c.recupererDonneesTousMois();
            c.caluclecartypeT();
               
                ecarttemp1.setText(""+c.getecartT());
                nebultemp1.setText(""+c.getecartN());
                humidtemp1.setText(""+c.getecartH());
            //c.affichegraph();
            x=c.getStationRecherchee();

            System.out.println("****************************** hehe  "+c.getStationRecherchee().get(0).getTemperature()) ;
            anne = annee2.getText();

            if(m.isEmpty()) m="";
            else   if(Integer.parseInt(m)<10) m=""+0+m;
            j = jour2.getText();
            Controller c1 = new Controller();
            c1.ChargerFichier();
            c1.RecupererDonneesFichier();
            c1.recupererDonneesTousMois();
               
                ecarttemp2.setText(""+c1.getecartT());
                nebultemp2.setText(""+c1.getecartN());
                humidtemp2.setText(""+c1.getecartH());
            x1=c1.getStationRecherchee();
            System.out.println("****************************** hehe  "+c1.getStationRecherchee().get(0).getTemperature()) ;

            // c1.affichegraph();
            manager manager = new manager();
            manager.comparaisongraph(x,x1,comp);

        } catch (IOException ex) {
            Logger.getLogger(Smarti.class.getName()).log(Level.SEVERE, null, ex);
        }
        }
         if(listcompmoisannee.getSelectedValue()=="Jour"){
                if(!(jour.getText().equals(jour2.getText()))){
            JOptionPane.showMessageDialog(null,
                "vous devez comparer 2 jours identiques ","warning"
                ,JOptionPane.WARNING_MESSAGE);
        }

        else{
            comp=listcomp.getSelectedValue();

            ArrayList<ReleveMeteo> x = new ArrayList<>();
            ArrayList<ReleveMeteo> x1 = new ArrayList<>();

            j = jour.getText();
            nom = (String) combo.getSelectedItem();
            anne = annee.getText();
            m = mois.getText();
            if(m.isEmpty()) {m="";}
            else if(Integer.parseInt(m)<10) {m=""+0+m;}

            Controller c = new Controller();
            try {ecarttemp1.setText("");
                nebultemp1.setText("");
                humidtemp1.setText("");

                c.ChargerFichier();
                c.RecupererDonneesFichier();
                c.recupererDonnees8Jour();
                c.caluclecartypeT();
                c.AfficherStation8Recherchee();
                 
                ecarttemp1.setText(""+c.getecartT());
                nebultemp1.setText(""+c.getecartN());
                humidtemp1.setText(""+c.getecartH());
                //c.affichegraph();
                x=c.getStationRecherchee();

                System.out.println("****************************** hehe  "+c.getStationRecherchee().get(0).getTemperature()) ;
                anne = annee2.getText();
                m = moi2.getText();
                if(m.isEmpty()) m="";
                else   if(Integer.parseInt(m)<10) m=""+0+m;
                j = jour2.getText();
                Controller c1 = new Controller();
                c1.ChargerFichier();
                c1.RecupererDonneesFichier();
                 c1.recupererDonnees8Jour();
                c1.caluclecartypeT();
                c1.AfficherStation8Recherchee();
               
                ecarttemp2.setText("");
                nebultemp2.setText("");
                humidtemp2.setText("");
                ecarttemp2.setText(""+c1.getecartT());
                nebultemp2.setText(""+c1.getecartN());
                humidtemp2.setText(""+c1.getecartH());
                x1=c1.getStationRecherchee();
                System.out.println("****************************** hehe  "+c1.getStationRecherchee().get(0).getTemperature()) ;

                // c1.affichegraph();
              
            } catch (IOException ex) {
                Logger.getLogger(Smarti.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnxtActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnxtActionPerformed

    private void btnstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnstActionPerformed
        Controller c = new Controller();
        c.Afficher();
    }//GEN-LAST:event_btnstActionPerformed

    private void btnaffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaffActionPerformed
        Controller c = new Controller();
        c.AffichertoutesStations();
    }//GEN-LAST:event_btnaffActionPerformed

    private void grapheAnneeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_grapheAnneeActionPerformed
        // TODO add your handling code here:
        Controller c = new Controller();
        c.recupererDonneesTousMois();
        // c.AfficheMoyenneTousMois();
        c.affichegraph();
    }//GEN-LAST:event_grapheAnneeActionPerformed

    private void graphMoisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_graphMoisActionPerformed
        // TODO add your handling code here:
        Controller c = new Controller();

        //c.AfficherStationMoyenneTousLesJours();

        if(!(mois.getText().isEmpty())){
            c.recupererDonneesTousjours();
            c.affichegraph();}
        else{
            JOptionPane.showMessageDialog(null,
                "vous devez entrer un mois puis cliquez sur charger ","warning"
                ,JOptionPane.WARNING_MESSAGE);

        }
    }//GEN-LAST:event_graphMoisActionPerformed

    private void afficherdonnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_afficherdonnActionPerformed
        // TODO add your handling code here:
        if(listemoyenne.getSelectedValue().equals("Mois")){
            m=mois.getText();
            if(Integer.parseInt(m)<10) m="0"+m;
            Controller c = new Controller();
            c.AfficheMoyenneMois();
            c.caluclecartypeT();
            
           
        }

        else if(listemoyenne.getSelectedValue().equals("Jour")){

            if(j.isEmpty()){
                JOptionPane.showMessageDialog(null,
                    "vous devez entrer un jour ","warning"
                    ,JOptionPane.WARNING_MESSAGE);}
            Controller c = new Controller();
            c.AfficherStationRecherchee();
        }
        else if(listemoyenne.getSelectedValue().equals("Jour Detaillé")){

            if(j.isEmpty()){
                JOptionPane.showMessageDialog(null,
                    "vous devez entrer un jour ","warning"
                    ,JOptionPane.WARNING_MESSAGE);}
            Controller c = new Controller();
            c.AfficherStation8Recherchee();
        }

        else if(listemoyenne.getSelectedValue().equals("Mois Detaillé")){
            m=mois.getText();
            if(Integer.parseInt(m)<10) m="0"+m;
            Controller c = new Controller();
            if(!(mois.getText().isEmpty()))
            c.AfficherStationMoyenneTousLesJours();
            else{
                JOptionPane.showMessageDialog(null,
                    "vous devez entrer un mois puis cliquez sur charger ","warning"
                    ,JOptionPane.WARNING_MESSAGE);

            }
            grapheAnnee.setEnabled(false);
            graphMois.setEnabled(true); c.caluclecartypeT();
            ecarttypeT.setText("");
            ecarttypeN.setText("");
            ecarttypeH.setText("");
           
            c.caluclecartypeT();
            ecarttypeT.setText(""+c.getecartT());
            ecarttypeN.setText(""+c.getecartN());
            ecarttypeH.setText(""+c.getecartH());
           

        }

        else if(listemoyenne.getSelectedValue().equals("Année Detaillée")){

            Controller c = new Controller();
            if(!(mois.getText().isEmpty())){

                try {
                    anne = annee.getText();
                    m="";
                    c.ChargerFichier();
                    c.RecupererDonneesFichier();
                    ecarttypeT.setText("");
                    ecarttypeN.setText("");
                    ecarttypeH.setText("");
                    c.caluclecartypeT();
                    ecarttypeT.setText(""+c.getecartT());
                    ecarttypeN.setText(""+c.getecartN());
                    ecarttypeH.setText(""+c.getecartH());
                    graphMois.setEnabled(false);
                    grapheAnnee.setEnabled(true);
                } catch (IOException ex) {
                    Logger.getLogger(Smarti.class.getName()).log(Level.SEVERE, null, ex);
                }
                graphMois.setEnabled(false);
                grapheAnnee.setEnabled(true);

            }

            c.AfficheMoyenneTousMois();
            graphMois.setEnabled(false);
            grapheAnnee.setEnabled(true);
           

        }
    }//GEN-LAST:event_afficherdonnActionPerformed

    private void btnloadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnloadActionPerformed

        nom = (String) combo.getSelectedItem();

        anne = annee.getText();
        m = mois.getText();
        if(m.isEmpty()) m="";
        else   if(Integer.parseInt(m)<10) m=""+0+m;

        j = jour.getText();

        try {
            Controller c = new Controller();
            c.ChargerFichier();
            c.RecupererDonneesFichier();

            // *******************
            //mohammed version
            // DownloadFile downloadFile = new DownloadFile(anne, m);
            // ********************

            btnaff.setEnabled(true);
            btnst.setEnabled(true);
            // btn1Stat.setEnabled(true);

        } catch (IOException ex) {
            Logger.getLogger(Smarti.class.getName()).log(Level.SEVERE, null, ex);
        }
        afficherdonn.setEnabled(true);
    }//GEN-LAST:event_btnloadActionPerformed

    private void btnconfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnconfActionPerformed
        Date d = new Date();
        jour.setText(""+jourcal.getDay());
        mois.setText(""+(moiscal.getMonth()+1));
        annee.setText(""+anneecal.getYear());
        btnload.setEnabled(true);
        /*    if(((Integer.parseInt(jour.getText()))>(d.getMonth()+1)) || (Integer.parseInt(annee.getText())>d.getYear()) ){

            JOptionPane.showMessageDialog(null,
                " veuillez saisr un mois et une année valide ","erreur date"
                ,JOptionPane.WARNING_MESSAGE);}
        */

        //JOptionPane.showMessageDialog(rootPane,calendar.getCalendar().get());
        //   jour.setText((String) calendar.getDayChooser());

        // TODO add your handling code here:
        // JCalendar j = new JCalendar();
        //j = calendar;
        //Date d = j.getCalendar().getTime();

        //JOptionPane.showMessageDialog(rootPane,calendar.getCalendar().get());
        //   jour.setText((String) calendar.getDayChooser());

        // TODO add your handling code here:
        // JCalendar j = new JCalendar();
        //j = calendar;
        //Date d = j.getCalendar().getTime();
    }//GEN-LAST:event_btnconfActionPerformed

    private void jourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jourActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jourActionPerformed

    private void moisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_moisActionPerformed

    private void comboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboActionPerformed

    private void ecarttypeTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ecarttypeTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ecarttypeTActionPerformed

    private void ecarttypeNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ecarttypeNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ecarttypeNActionPerformed

    private void ecarttypeHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ecarttypeHActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ecarttypeHActionPerformed

    private void ecarttemp1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ecarttemp1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ecarttemp1ActionPerformed

    private void humidtemp1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_humidtemp1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_humidtemp1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Smarti.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Smarti.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Smarti.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Smarti.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Smarti().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton afficherdonn;
    private javax.swing.JTextField annee;
    private javax.swing.JTextField annee2;
    private com.toedter.calendar.JYearChooser anneecal;
    private com.toedter.calendar.JYearChooser anneecal2;
    private javax.swing.JButton btnaff;
    private javax.swing.JButton btnconf;
    private javax.swing.JButton btnconf2;
    private javax.swing.JButton btnload;
    private javax.swing.JButton btnst;
    private javax.swing.JButton btnxt;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup10;
    private javax.swing.ButtonGroup buttonGroup11;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.ButtonGroup buttonGroup6;
    private javax.swing.ButtonGroup buttonGroup7;
    private javax.swing.ButtonGroup buttonGroup8;
    private javax.swing.ButtonGroup buttonGroup9;
    private javax.swing.JComboBox<String> combo;
    private javax.swing.JTextField ecarttemp1;
    private javax.swing.JTextField ecarttemp2;
    private javax.swing.JTextField ecarttypeH;
    private javax.swing.JTextField ecarttypeN;
    private javax.swing.JTextField ecarttypeT;
    private javax.swing.JButton graphMois;
    private javax.swing.JButton grapheAnnee;
    private javax.swing.JTextField humidtemp1;
    private javax.swing.JTextField humidtemp2;
    private javax.swing.JButton jButton2;
    private javax.swing.JColorChooser jColorChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jour;
    private javax.swing.JTextField jour2;
    private com.toedter.calendar.JDayChooser jourcal;
    private com.toedter.calendar.JDayChooser jourcal2;
    private javax.swing.JLabel lblannee;
    private javax.swing.JLabel lbmois;
    private javax.swing.JLabel lbstation;
    private javax.swing.JList<String> listcomp;
    private javax.swing.JList<String> listcompmoisannee;
    private javax.swing.JList<String> listemoyenne;
    private javax.swing.JTextField moi2;
    private javax.swing.JTextField mois;
    private javax.swing.JPanel mois2;
    private com.toedter.calendar.JMonthChooser moiscal;
    private com.toedter.calendar.JMonthChooser moiscal2;
    private javax.swing.JTextField nebultemp1;
    private javax.swing.JTextField nebultemp2;
    // End of variables declaration//GEN-END:variables
}
